/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerProducto;
import Controller.ControllerProveedor;
import Controller.ControllerUsuario;
import javax.swing.plaf.DesktopPaneUI;

/**
 *
 * @author joshu
 */
public class frmpaginaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmpaginaprincipal
     */
    public frmpaginaprincipal(String idUsuario, String nombreUsuario, String tipoUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("SISTEMA DE INVENTARIO DE PRODUCTOS");
        IdUsuariolbl.setText(idUsuario);
        lblNombreUsuario.setText(nombreUsuario);
        lblTipoUsuario.setText(tipoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        IdUsuariolbl = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        menuCatalogoDatos = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenuItem();
        btnProveedores = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        btnInventarioProductos = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        btnProductosCaducidad = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        btnAcardeDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IdUsuariolbl.setText("ID USUARIO");

        lblNombreUsuario.setText("NOMBRE USUARIO");

        lblTipoUsuario.setText("TIPO USUARIO");

        jDesktopPane.setLayer(IdUsuariolbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IdUsuariolbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(871, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(IdUsuariolbl)
                .addGap(18, 18, 18)
                .addComponent(lblNombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblTipoUsuario)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        menufile.setText("File");

        btnSalir.setText("Salir");
        menufile.add(btnSalir);

        jMenuBar.add(menufile);

        menuCatalogoDatos.setText("Catalogo De Datos");
        menuCatalogoDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCatalogoDatosActionPerformed(evt);
            }
        });

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnUsuarios);

        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnProveedores);

        jMenuBar.add(menuCatalogoDatos);

        menuProcesos.setText("Procesos");
        menuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosActionPerformed(evt);
            }
        });

        btnInventarioProductos.setText("Inventario de Productos");
        btnInventarioProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioProductosActionPerformed(evt);
            }
        });
        menuProcesos.add(btnInventarioProductos);

        jMenuBar.add(menuProcesos);

        menuReportes.setText("Reportes");

        btnProductosCaducidad.setText("Productos por Fecha de Caducidad");
        menuReportes.add(btnProductosCaducidad);

        jMenuBar.add(menuReportes);

        menuAyuda.setText("Ayuda");

        btnAcardeDe.setText("Acerca de");
        menuAyuda.add(btnAcardeDe);

        jMenuBar.add(menuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
    Usuarios obj= new Usuarios ();
    jDesktopPane.add(obj);
    ControllerUsuario con = new ControllerUsuario(obj);//conectamos controller con frm
    con.iniciar();
    obj.toFront();
    obj.setLocation(jDesktopPane.getWidth() / 2 - obj.getWidth() / 2, jDesktopPane.getHeight() / 2 - obj.getHeight() / 2);
    obj.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
     Proveedores obj = new Proveedores();
     jDesktopPane.add(obj);
     ControllerProveedor con = new ControllerProveedor(obj);
     con.iniciar();
     obj.toFront();
     obj.setLocation(jDesktopPane.getWidth() / 2 - obj.getWidth() / 2, jDesktopPane.getHeight() / 2 - obj.getHeight() / 2);
     obj.setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnInventarioProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioProductosActionPerformed
     InventarioDeProductos obj = new InventarioDeProductos();
    jDesktopPane.add(obj);
    ControllerProducto con = new ControllerProducto (obj);
    obj.toFront();
    obj.setLocation(jDesktopPane.getWidth() / 2 - obj.getWidth() / 2, jDesktopPane.getHeight() / 2 - obj.getHeight() / 2);
    obj.setVisible(true);
    }//GEN-LAST:event_btnInventarioProductosActionPerformed

    private void menuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosActionPerformed

    }//GEN-LAST:event_menuProcesosActionPerformed

    private void menuCatalogoDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCatalogoDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCatalogoDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel IdUsuariolbl;
    private javax.swing.JMenuItem btnAcardeDe;
    private javax.swing.JMenuItem btnInventarioProductos;
    private javax.swing.JMenuItem btnProductosCaducidad;
    private javax.swing.JMenuItem btnProveedores;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCatalogoDatos;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menufile;
    // End of variables declaration//GEN-END:variables
}
